### ISSUE TITLE
Compiler relative path on mac

### ISSUE THREAD

**Issue by d-riggas** [CordMaster/basic-java-compile#1]
After installing package basic-java-compile on Atom on MacOS and having set $JAVA_HOME in .bash_profile, while attempting to compile a .java file, I kept getting error: 

> /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/**\bin\javac**' could not be spawned. Is it installed and on your path?

**Fix:** 
Edited <basic-java-compile>/lib/compile-handler.js statements:

> Line 31: this.compileProc = spawn(javaPath + '\\bin\\' + 'javac', [fullName], { cwd: workingDir });

on lines 

> Line 50: this.execProc = spawn(javaPath + '\\bin\\' + 'java', [filename], { cwd: workingDir });

changing '\\bin\\' to '/bin/'.

Please update source code to take platform path delimiter into account.

**Comment by gasssston** [comment]
Hello, i have that problem and I don't understand what I need to do to fix this error. 

First of all, where is the directory '/lib'? (PD: I'm new on MAC :D)

**Comment by gasssston** [comment]
After the changes, it worked?

**Comment by riggas-ionio** [comment]
Yes, after the changes described above, it worked.

Yet, if you are not interested in fixing this yourself, you could use this alternative which fixes this for Mac or Linux (but breaks it for Win; LOL): https://atom.io/packages/basic-java-compile-nix
Essentially it has applied the changes described above and repackaged it.

**Comment by gasssston** [comment]
Wow, okay. Thank you so much!!😁🖥️💻

**Comment by CordMaster** [comment]
The fix has been applied! Thanks so much, @d-riggas!
