### ISSUE TITLE
Uncaught Error: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by a-chhajed** [CordMaster/basic-java-compile#10]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [basic-java-compile](https://github.com/CordMaster/basic-java-compile) package 0.5.0

### Stack Trace

Uncaught Error: Cannot call write after a stream was destroyed

```
At events.js:200

Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:431:19)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at Object.write (/packages/basic-java-compile/lib/compile-handler.js:82:27)
    at /packages/basic-java-compile/lib/basic-java-compile.js:114:24)
    at HTMLInputElement.dispatch (/packages/basic-java-compile/node_modules/jquery/dist/jquery.js:5430:27)
    at HTMLInputElement.elemData.handle (/packages/basic-java-compile/node_modules/jquery/dist/jquery.js:5234:28)
```

### Commands

```
     -7:39 basic-java-compile:run-file (div.line)
     -7:00.5.0 basic-java-compile:run (div.line)
     -6:10.2.0 basic-java-compile:run-file (div.line)
     -6:05.2.0 fuzzy-finder:toggle-git-status-finder (div.tool-panel.tree-view)
     -6:01.1.0 script:run (input.hidden-input)
     -5:54.6.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:29.3.0 basic-java-compile:run-file (input.hidden-input)
     -4:46.2.0 basic-java-compile:run (div.line)
     -4:33.4.0 symbols-view:toggle-project-symbols (input.hidden-input)
  3x -4:30 basic-java-compile:run (input.hidden-input)
     -1:21.3.0 settings-view:install-packages-and-themes (input.hidden-input)
  5x -1:17.6.0 core:backspace (input.hidden-input)
     -1:14.6.0 core:confirm (input.hidden-input)
     -0:11.5.0 basic-java-compile:run-file (div.line.cursor-line)
```

### Non-Core Packages

```
basic-java-compile 0.5.0 
ide-java 0.9.1 
script-fudan 237.2.0 
```

**Comment by CordMaster** [comment]
Hello! Thanks for the report; however I am not entirely sure what went wrong or what steps were taken to cause this issue. That said, due to the (sunsetting)[https://github.blog/2022-06-08-sunsetting-atom] of Atom planned for December of 2022, I no longer plan to support this extension. I would strongly recommend moving to Visual Studio Code and using the Java (extension)[https://code.visualstudio.com/docs/languages/java].

**Comment by CordMaster** [comment]
I believe I have found a fix for what I think the error is, but I cannot push it to the Atom repo due to what seems to be a bug in their system. You can still download the code and install the extension by hand if you'd like.

--Edit--
I *think* I got it to publish.
