### ISSUE TITLE
java compiling error

### ISSUE THREAD

**Issue by Fcastroa1** [CordMaster/basic-java-compile#2]
after installing a basic java compile i'm getting this error:

C:\Program Files\Java\jdk1.8.0_25\bin\bin\javac' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
and i already installed the path

**Comment by CordMaster** [comment]
Try changing your JAVA_HOME from "C:\Program Files\Java\jdk-x.x.x\bin" to just "C:\Program Files\Java\jdk-x.x.x"
