### ISSUE TITLE
Garbled characters appear when displaying Chinese output

### ISSUE THREAD

**Issue by GhostHjh** [CordMaster/basic-java-compile#5]
The java file uses ANSI encoding, and the encoding of atom is Chinese (GB18030). When using this plugin to compile and run, if there is Chinese in the returned result, it will show garbled characters.
![image](https://user-images.githubusercontent.com/56105932/95890498-7569a980-0db6-11eb-9fa8-a37dd06c3da0.png)

**Comment by CordMaster** [comment]
Thanks for the report! There is indeed an error with the handling of the encodings - I have created a fix, and will publish it in a bit!

**Comment by CordMaster** [comment]
0.3.0 has been published with support for command line parameters. To fix your problem, try enabling Unicode support using these new options:

JavacArgs: -encoding utf8
Java Args: -Dfile.encoding=UTF8

See attached screenshots for more info
(I probably used nonsense Chinese characters, sorry :/)

![image](https://user-images.githubusercontent.com/38766223/95909225-5f7acb00-0d5b-11eb-9d71-67fdfd8588e6.png)

![image](https://user-images.githubusercontent.com/38766223/95909275-702b4100-0d5b-11eb-8548-a54b4f69350a.png)
